# ─── Site Settings ───────────────────────────────────────────────
title: CV
url: 'http://www.alicialcaide.com'
description: Personal CV Website

# ─── Sass ────────────────────────────────────────────────────────
sass:
  sass_dir: _sass
  style: compressed

# ─── Build ───────────────────────────────────────────────────────
encoding: "utf-8"
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sh"
